customhost = "employee.ceygv0gzptju.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "bait3273"
customdb = "employee"
custombucket = "cqz-employee"
customregion = "us-east-1"
cloudfront = "dghrg9e97uuwl.cloudfront.net"
