customhost = "employee.cqnylupfswyh.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "bait3273"
customdb = "employee"
custombucket = "yongkangjeff-employee"
customregion = "us-east-1"
